In [ ]:
# Input text
words = ["NLP", "is", "fun"]

# Create vocabulary
vocab = list(set(words))

# One-hot encoding
one_hot_vectors = {}

for word in vocab:
    vector = [0] * len(vocab)
    index = vocab.index(word)
    vector[index] = 1
    one_hot_vectors[word] = vector

# Display output
for word, vector in one_hot_vectors.items():
    print(word, ":", vector)


fun : [1, 0, 0]
is : [0, 1, 0]
NLP : [0, 0, 1]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Input sentences
sentences = [
    "NLP is fun",
    "NLP is easy"
]

# Create Bag of Words model
vectorizer = CountVectorizer()

# Transform text into BoW vectors
bow = vectorizer.fit_transform(sentences)

# Display vocabulary and vectors
print("Vocabulary:", vectorizer.get_feature_names_out())
print("Bag of Words Matrix:\n", bow.toarray())


Vocabulary: ['easy' 'fun' 'is' 'nlp']
Bag of Words Matrix:
 [[0 1 1 1]
 [1 0 1 1]]


In [ ]:
!pip install gensim


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 43.6 MB/s eta 0:00:00


In [ ]:
from gensim.models import Word2Vec

# Input sentences
sentences = [
    ["nlp", "is", "fun"],
    ["nlp", "is", "easy"],
    ["machine", "learning", "is", "powerful"]
]

# Train Word2Vec model
model = Word2Vec(sentences, vector_size=50, window=3, min_count=1)

# Get vector for a word
vector = model.wv["nlp"]

# Display vector
print("Vector for 'nlp':")
print(vector)

Vector for 'nlp':
[-0.01631583  0.0089916  -0.00827415  0.00164907  0.01699724 -0.00892435
  0.009035   -0.01357392 -0.00709698  0.01879702 -0.00315531  0.00064274
 -0.00828126 -0.01536538 -0.00301602  0.00493959 -0.00177605  0.01106732
 -0.00548595  0.00452013  0.01091159  0.01669191 -0.00290748 -0.01841629
  0.0087411   0.00114357  0.01488382 -0.00162657 -0.00527683 -0.01750602
 -0.00171311  0.00565313  0.01080286  0.01410531 -0.01140624  0.00371764
  0.01217773 -0.0095961  -0.00621452  0.01359526  0.00326295  0.00037983
  0.00694727  0.00043555  0.01923765  0.01012121 -0.01783478 -0.01408312
  0.00180291  0.01278507]


In [ ]:
import gensim.downloader as api

# Load pre-trained GloVe model
glove_model = api.load("glove-wiki-gigaword-50")

# Get embedding for a word
vector = glove_model["nlp"]

# Display vector
print("GloVe vector for 'nlp':")
print(vector)


[==================================================] 100.0% 66.0/66.0MB downloaded
GloVe vector for 'nlp':
[-0.6721    -0.17858    0.20188    0.63581   -0.31304    1.2183
 -0.13314   -1.1776    -0.27009    0.52236   -0.0086308 -0.056211
  1.3483    -1.0131    -1.0985    -0.24086   -0.0066808 -0.14822
 -0.044672   0.54472   -0.92966   -0.69065    0.91675    0.054691
 -0.2081     1.1201     0.92071   -1.2295     0.107      0.65846
 -0.84775   -0.14577   -0.69941    0.83514    0.90995   -0.70647
 -0.78513    0.82611    1.0785     0.29806    1.0306     0.19589
 -0.5562     0.43684    0.5979     0.77427    0.40238    0.57069
  0.29321    1.0723   ]


In [ ]:
from transformers import BertTokenizer, BertModel
import torch

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

# Input text
text = "Natural Language Processing is interesting"

# Tokenize input
inputs = tokenizer(text, return_tensors="pt")

# Generate embeddings
with torch.no_grad():
    outputs = model(**inputs)

# Get sentence embedding (CLS token)
sentence_embedding = outputs.last_hidden_state[:, 0, :]

print("BERT Embedding:")
print(sentence_embedding)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BERT Embedding:
tensor([[-2.5250e-01, -2.4053e-02, -2.3873e-01,  1.5428e-01, -3.3861e-01,
         -3.5762e-01,  2.5491e-01,  6.7699e-01, -2.4066e-01, -4.6071e-01,
         -8.5395e-02, -2.4359e-01, -3.3299e-02,  5.4060e-02,  1.0546e-01,
          5.5594e-02, -1.2216e-01,  4.6366e-01,  2.0595e-01, -9.7257e-02,
          3.0154e-02, -1.3629e-01, -5.9478e-02, -1.7364e-01,  1.8538e-01,
         -4.6238e-01,  1.2059e-01,  4.9853e-02,  2.3847e-01, -7.3036e-02,
         -2.4131e-01,  3.6028e-01, -1.9017e-01, -2.8902e-01,  2.7089e-01,
         -9.9592e-02,  1.6517e-01, -1.3882e-01,  2.1839e-01,  1.7944e-01,
         -7.3715e-03,  2.0296e-01,  8.8514e-02,  6.8726e-02, -4.1260e-01,
         -2.7561e-01, -2.2558e+00, -1.4753e-02, -2.7646e-01, -4.1014e-01,
          5.7583e-02, -1.5857e-01,  6.3458e-01,  4.0190e-01,  5.3158e-02,
          2.3120e-01, -1.2199e-01,  7.1629e-01,  3.5322e-01,  2.8817e-01,
          5.7305e-03, -2.2648e-01, -2.7725e-01, -2.2371e-01,  1.1778e-01,
          2.5062e-01, 